---
- hosts: all
  become: yes
  vars:
    users:
      - username: test
        visual_studio_code_extensions:
          - ms-python.python
          - ms-vscode.cpptools
          - espressif.esp-idf-extension
          - eamodio.gitlens
          - GitHub.copilot
  pre_tasks:
    - name: Ensure 'acl' package is installed
      package:
        name: acl
        state: present
  roles:
    - role: gantsign.postman
    - role: geerlingguy.mysql
      vars:
        mysql_root_password: "root_password"
        mysql_databases:
          - name: database_name
        mysql_users:
          - name: db_user
            password: "db_password"
            priv: "database_name.*:ALL"
#    - role: gantsign.visual-studio-code
#    - role: gantsign.visual-studio-code-extensions
    - role: darkwizard242.googlechrome
    - role: geerlingguy.java
    - role: geerlingguy.nodejs

